name: Immutables
highlighter: pygments
markdown: redcarpet
exclude: [README.md]

# latest version available in templates under site.v
v: 2.8.1

# rootUri for maven central artifactId
depUri: https://search.maven.org/artifact/org.immutables

